spring.application.name=api-gateway

server.port=${PORT:8765}

spring.cloud.gateway.routes[0].id=question-service
spring.cloud.gateway.routes[0].uri=${QUESTION_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/question/**

spring.cloud.gateway.routes[1].id=quiz-service
spring.cloud.gateway.routes[1].uri=${QUIZ_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/quiz/**

spring.cloud.gateway.routes[2].id=result-service
spring.cloud.gateway.routes[2].uri=${RESULT_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/result/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
